// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/ai/ai.proto

package ai

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIService_AnalyzeAdmissionChances_FullMethodName = "/ai.AIService/AnalyzeAdmissionChances"
	AIService_GenerateRoadmap_FullMethodName         = "/ai.AIService/GenerateRoadmap"
	AIService_ReviewEssay_FullMethodName             = "/ai.AIService/ReviewEssay"
	AIService_MatchGrants_FullMethodName             = "/ai.AIService/MatchGrants"
	AIService_GetAnalysisHistory_FullMethodName      = "/ai.AIService/GetAnalysisHistory"
)

// AIServiceClient is the client API for AIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIServiceClient interface {
	AnalyzeAdmissionChances(ctx context.Context, in *AnalyzeAdmissionChancesRequest, opts ...grpc.CallOption) (*AnalyzeAdmissionChancesResponse, error)
	GenerateRoadmap(ctx context.Context, in *GenerateRoadmapRequest, opts ...grpc.CallOption) (*GenerateRoadmapResponse, error)
	ReviewEssay(ctx context.Context, in *ReviewEssayRequest, opts ...grpc.CallOption) (*ReviewEssayResponse, error)
	MatchGrants(ctx context.Context, in *MatchGrantsRequest, opts ...grpc.CallOption) (*MatchGrantsResponse, error)
	GetAnalysisHistory(ctx context.Context, in *GetAnalysisHistoryRequest, opts ...grpc.CallOption) (*GetAnalysisHistoryResponse, error)
}

type aIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIServiceClient(cc grpc.ClientConnInterface) AIServiceClient {
	return &aIServiceClient{cc}
}

func (c *aIServiceClient) AnalyzeAdmissionChances(ctx context.Context, in *AnalyzeAdmissionChancesRequest, opts ...grpc.CallOption) (*AnalyzeAdmissionChancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeAdmissionChancesResponse)
	err := c.cc.Invoke(ctx, AIService_AnalyzeAdmissionChances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) GenerateRoadmap(ctx context.Context, in *GenerateRoadmapRequest, opts ...grpc.CallOption) (*GenerateRoadmapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateRoadmapResponse)
	err := c.cc.Invoke(ctx, AIService_GenerateRoadmap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) ReviewEssay(ctx context.Context, in *ReviewEssayRequest, opts ...grpc.CallOption) (*ReviewEssayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReviewEssayResponse)
	err := c.cc.Invoke(ctx, AIService_ReviewEssay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) MatchGrants(ctx context.Context, in *MatchGrantsRequest, opts ...grpc.CallOption) (*MatchGrantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MatchGrantsResponse)
	err := c.cc.Invoke(ctx, AIService_MatchGrants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) GetAnalysisHistory(ctx context.Context, in *GetAnalysisHistoryRequest, opts ...grpc.CallOption) (*GetAnalysisHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAnalysisHistoryResponse)
	err := c.cc.Invoke(ctx, AIService_GetAnalysisHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIServiceServer is the server API for AIService service.
// All implementations must embed UnimplementedAIServiceServer
// for forward compatibility.
type AIServiceServer interface {
	AnalyzeAdmissionChances(context.Context, *AnalyzeAdmissionChancesRequest) (*AnalyzeAdmissionChancesResponse, error)
	GenerateRoadmap(context.Context, *GenerateRoadmapRequest) (*GenerateRoadmapResponse, error)
	ReviewEssay(context.Context, *ReviewEssayRequest) (*ReviewEssayResponse, error)
	MatchGrants(context.Context, *MatchGrantsRequest) (*MatchGrantsResponse, error)
	GetAnalysisHistory(context.Context, *GetAnalysisHistoryRequest) (*GetAnalysisHistoryResponse, error)
	mustEmbedUnimplementedAIServiceServer()
}

// UnimplementedAIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIServiceServer struct{}

func (UnimplementedAIServiceServer) AnalyzeAdmissionChances(context.Context, *AnalyzeAdmissionChancesRequest) (*AnalyzeAdmissionChancesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeAdmissionChances not implemented")
}
func (UnimplementedAIServiceServer) GenerateRoadmap(context.Context, *GenerateRoadmapRequest) (*GenerateRoadmapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateRoadmap not implemented")
}
func (UnimplementedAIServiceServer) ReviewEssay(context.Context, *ReviewEssayRequest) (*ReviewEssayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReviewEssay not implemented")
}
func (UnimplementedAIServiceServer) MatchGrants(context.Context, *MatchGrantsRequest) (*MatchGrantsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MatchGrants not implemented")
}
func (UnimplementedAIServiceServer) GetAnalysisHistory(context.Context, *GetAnalysisHistoryRequest) (*GetAnalysisHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAnalysisHistory not implemented")
}
func (UnimplementedAIServiceServer) mustEmbedUnimplementedAIServiceServer() {}
func (UnimplementedAIServiceServer) testEmbeddedByValue()                   {}

// UnsafeAIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIServiceServer will
// result in compilation errors.
type UnsafeAIServiceServer interface {
	mustEmbedUnimplementedAIServiceServer()
}

func RegisterAIServiceServer(s grpc.ServiceRegistrar, srv AIServiceServer) {
	// If the following call panics, it indicates UnimplementedAIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIService_ServiceDesc, srv)
}

func _AIService_AnalyzeAdmissionChances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeAdmissionChancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).AnalyzeAdmissionChances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_AnalyzeAdmissionChances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).AnalyzeAdmissionChances(ctx, req.(*AnalyzeAdmissionChancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_GenerateRoadmap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRoadmapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).GenerateRoadmap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_GenerateRoadmap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).GenerateRoadmap(ctx, req.(*GenerateRoadmapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_ReviewEssay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewEssayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).ReviewEssay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_ReviewEssay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).ReviewEssay(ctx, req.(*ReviewEssayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_MatchGrants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchGrantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).MatchGrants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_MatchGrants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).MatchGrants(ctx, req.(*MatchGrantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_GetAnalysisHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnalysisHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).GetAnalysisHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_GetAnalysisHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).GetAnalysisHistory(ctx, req.(*GetAnalysisHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIService_ServiceDesc is the grpc.ServiceDesc for AIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.AIService",
	HandlerType: (*AIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeAdmissionChances",
			Handler:    _AIService_AnalyzeAdmissionChances_Handler,
		},
		{
			MethodName: "GenerateRoadmap",
			Handler:    _AIService_GenerateRoadmap_Handler,
		},
		{
			MethodName: "ReviewEssay",
			Handler:    _AIService_ReviewEssay_Handler,
		},
		{
			MethodName: "MatchGrants",
			Handler:    _AIService_MatchGrants_Handler,
		},
		{
			MethodName: "GetAnalysisHistory",
			Handler:    _AIService_GetAnalysisHistory_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ai/ai.proto",
}
