// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/ai/ai.proto

package ai

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AnalyzeAdmissionChancesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UniversityId  string                 `protobuf:"bytes,2,opt,name=university_id,json=universityId,proto3" json:"university_id,omitempty"`
	Gpa           float32                `protobuf:"fixed32,3,opt,name=gpa,proto3" json:"gpa,omitempty"`
	SatScore      int32                  `protobuf:"varint,4,opt,name=sat_score,json=satScore,proto3" json:"sat_score,omitempty"`
	IeltsScore    float32                `protobuf:"fixed32,5,opt,name=ielts_score,json=ieltsScore,proto3" json:"ielts_score,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnalyzeAdmissionChancesRequest) Reset() {
	*x = AnalyzeAdmissionChancesRequest{}
	mi := &file_proto_ai_ai_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeAdmissionChancesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeAdmissionChancesRequest) ProtoMessage() {}

func (x *AnalyzeAdmissionChancesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeAdmissionChancesRequest.ProtoReflect.Descriptor instead.
func (*AnalyzeAdmissionChancesRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{0}
}

func (x *AnalyzeAdmissionChancesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *AnalyzeAdmissionChancesRequest) GetUniversityId() string {
	if x != nil {
		return x.UniversityId
	}
	return ""
}

func (x *AnalyzeAdmissionChancesRequest) GetGpa() float32 {
	if x != nil {
		return x.Gpa
	}
	return 0
}

func (x *AnalyzeAdmissionChancesRequest) GetSatScore() int32 {
	if x != nil {
		return x.SatScore
	}
	return 0
}

func (x *AnalyzeAdmissionChancesRequest) GetIeltsScore() float32 {
	if x != nil {
		return x.IeltsScore
	}
	return 0
}

type AnalyzeAdmissionChancesResponse struct {
	state                     protoimpl.MessageState `protogen:"open.v1"`
	AdmissionChancePercentage float32                `protobuf:"fixed32,1,opt,name=admission_chance_percentage,json=admissionChancePercentage,proto3" json:"admission_chance_percentage,omitempty"`
	WeakAreas                 []string               `protobuf:"bytes,2,rep,name=weak_areas,json=weakAreas,proto3" json:"weak_areas,omitempty"`
	ImprovementSuggestions    []string               `protobuf:"bytes,3,rep,name=improvement_suggestions,json=improvementSuggestions,proto3" json:"improvement_suggestions,omitempty"`
	GapAnalysis               string                 `protobuf:"bytes,4,opt,name=gap_analysis,json=gapAnalysis,proto3" json:"gap_analysis,omitempty"`
	unknownFields             protoimpl.UnknownFields
	sizeCache                 protoimpl.SizeCache
}

func (x *AnalyzeAdmissionChancesResponse) Reset() {
	*x = AnalyzeAdmissionChancesResponse{}
	mi := &file_proto_ai_ai_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnalyzeAdmissionChancesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnalyzeAdmissionChancesResponse) ProtoMessage() {}

func (x *AnalyzeAdmissionChancesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnalyzeAdmissionChancesResponse.ProtoReflect.Descriptor instead.
func (*AnalyzeAdmissionChancesResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{1}
}

func (x *AnalyzeAdmissionChancesResponse) GetAdmissionChancePercentage() float32 {
	if x != nil {
		return x.AdmissionChancePercentage
	}
	return 0
}

func (x *AnalyzeAdmissionChancesResponse) GetWeakAreas() []string {
	if x != nil {
		return x.WeakAreas
	}
	return nil
}

func (x *AnalyzeAdmissionChancesResponse) GetImprovementSuggestions() []string {
	if x != nil {
		return x.ImprovementSuggestions
	}
	return nil
}

func (x *AnalyzeAdmissionChancesResponse) GetGapAnalysis() string {
	if x != nil {
		return x.GapAnalysis
	}
	return ""
}

type GenerateRoadmapRequest struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	UserId                 string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	TargetUniversityId     string                 `protobuf:"bytes,2,opt,name=target_university_id,json=targetUniversityId,proto3" json:"target_university_id,omitempty"`
	MonthsUntilApplication int32                  `protobuf:"varint,3,opt,name=months_until_application,json=monthsUntilApplication,proto3" json:"months_until_application,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *GenerateRoadmapRequest) Reset() {
	*x = GenerateRoadmapRequest{}
	mi := &file_proto_ai_ai_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRoadmapRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRoadmapRequest) ProtoMessage() {}

func (x *GenerateRoadmapRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRoadmapRequest.ProtoReflect.Descriptor instead.
func (*GenerateRoadmapRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{2}
}

func (x *GenerateRoadmapRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *GenerateRoadmapRequest) GetTargetUniversityId() string {
	if x != nil {
		return x.TargetUniversityId
	}
	return ""
}

func (x *GenerateRoadmapRequest) GetMonthsUntilApplication() int32 {
	if x != nil {
		return x.MonthsUntilApplication
	}
	return 0
}

type GenerateRoadmapResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Steps         []*RoadmapStep         `protobuf:"bytes,1,rep,name=steps,proto3" json:"steps,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateRoadmapResponse) Reset() {
	*x = GenerateRoadmapResponse{}
	mi := &file_proto_ai_ai_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateRoadmapResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateRoadmapResponse) ProtoMessage() {}

func (x *GenerateRoadmapResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateRoadmapResponse.ProtoReflect.Descriptor instead.
func (*GenerateRoadmapResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{3}
}

func (x *GenerateRoadmapResponse) GetSteps() []*RoadmapStep {
	if x != nil {
		return x.Steps
	}
	return nil
}

type RoadmapStep struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Title         string                 `protobuf:"bytes,1,opt,name=title,proto3" json:"title,omitempty"`
	Description   string                 `protobuf:"bytes,2,opt,name=description,proto3" json:"description,omitempty"`
	MonthNumber   int32                  `protobuf:"varint,3,opt,name=month_number,json=monthNumber,proto3" json:"month_number,omitempty"`
	Category      string                 `protobuf:"bytes,4,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RoadmapStep) Reset() {
	*x = RoadmapStep{}
	mi := &file_proto_ai_ai_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RoadmapStep) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RoadmapStep) ProtoMessage() {}

func (x *RoadmapStep) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RoadmapStep.ProtoReflect.Descriptor instead.
func (*RoadmapStep) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{4}
}

func (x *RoadmapStep) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *RoadmapStep) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *RoadmapStep) GetMonthNumber() int32 {
	if x != nil {
		return x.MonthNumber
	}
	return 0
}

func (x *RoadmapStep) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type ReviewEssayRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	UserId         string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	EssayText      string                 `protobuf:"bytes,2,opt,name=essay_text,json=essayText,proto3" json:"essay_text,omitempty"`
	UniversityName string                 `protobuf:"bytes,3,opt,name=university_name,json=universityName,proto3" json:"university_name,omitempty"`
	ProgramName    string                 `protobuf:"bytes,4,opt,name=program_name,json=programName,proto3" json:"program_name,omitempty"`
	WordLimit      int32                  `protobuf:"varint,5,opt,name=word_limit,json=wordLimit,proto3" json:"word_limit,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *ReviewEssayRequest) Reset() {
	*x = ReviewEssayRequest{}
	mi := &file_proto_ai_ai_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewEssayRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewEssayRequest) ProtoMessage() {}

func (x *ReviewEssayRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewEssayRequest.ProtoReflect.Descriptor instead.
func (*ReviewEssayRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{5}
}

func (x *ReviewEssayRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *ReviewEssayRequest) GetEssayText() string {
	if x != nil {
		return x.EssayText
	}
	return ""
}

func (x *ReviewEssayRequest) GetUniversityName() string {
	if x != nil {
		return x.UniversityName
	}
	return ""
}

func (x *ReviewEssayRequest) GetProgramName() string {
	if x != nil {
		return x.ProgramName
	}
	return ""
}

func (x *ReviewEssayRequest) GetWordLimit() int32 {
	if x != nil {
		return x.WordLimit
	}
	return 0
}

type ReviewEssayResponse struct {
	state                  protoimpl.MessageState `protogen:"open.v1"`
	GrammarScore           float32                `protobuf:"fixed32,1,opt,name=grammar_score,json=grammarScore,proto3" json:"grammar_score,omitempty"`
	CoherenceScore         float32                `protobuf:"fixed32,2,opt,name=coherence_score,json=coherenceScore,proto3" json:"coherence_score,omitempty"`
	UniquenessScore        float32                `protobuf:"fixed32,3,opt,name=uniqueness_score,json=uniquenessScore,proto3" json:"uniqueness_score,omitempty"`
	RelevanceScore         float32                `protobuf:"fixed32,4,opt,name=relevance_score,json=relevanceScore,proto3" json:"relevance_score,omitempty"`
	ImprovementSuggestions []string               `protobuf:"bytes,5,rep,name=improvement_suggestions,json=improvementSuggestions,proto3" json:"improvement_suggestions,omitempty"`
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *ReviewEssayResponse) Reset() {
	*x = ReviewEssayResponse{}
	mi := &file_proto_ai_ai_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReviewEssayResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReviewEssayResponse) ProtoMessage() {}

func (x *ReviewEssayResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReviewEssayResponse.ProtoReflect.Descriptor instead.
func (*ReviewEssayResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{6}
}

func (x *ReviewEssayResponse) GetGrammarScore() float32 {
	if x != nil {
		return x.GrammarScore
	}
	return 0
}

func (x *ReviewEssayResponse) GetCoherenceScore() float32 {
	if x != nil {
		return x.CoherenceScore
	}
	return 0
}

func (x *ReviewEssayResponse) GetUniquenessScore() float32 {
	if x != nil {
		return x.UniquenessScore
	}
	return 0
}

func (x *ReviewEssayResponse) GetRelevanceScore() float32 {
	if x != nil {
		return x.RelevanceScore
	}
	return 0
}

func (x *ReviewEssayResponse) GetImprovementSuggestions() []string {
	if x != nil {
		return x.ImprovementSuggestions
	}
	return nil
}

type MatchGrantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Gpa           float32                `protobuf:"fixed32,2,opt,name=gpa,proto3" json:"gpa,omitempty"`
	Country       string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	Achievements  []string               `protobuf:"bytes,4,rep,name=achievements,proto3" json:"achievements,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MatchGrantsRequest) Reset() {
	*x = MatchGrantsRequest{}
	mi := &file_proto_ai_ai_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchGrantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchGrantsRequest) ProtoMessage() {}

func (x *MatchGrantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchGrantsRequest.ProtoReflect.Descriptor instead.
func (*MatchGrantsRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{7}
}

func (x *MatchGrantsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *MatchGrantsRequest) GetGpa() float32 {
	if x != nil {
		return x.Gpa
	}
	return 0
}

func (x *MatchGrantsRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *MatchGrantsRequest) GetAchievements() []string {
	if x != nil {
		return x.Achievements
	}
	return nil
}

type MatchGrantsResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	MatchedGrantIds []string               `protobuf:"bytes,1,rep,name=matched_grant_ids,json=matchedGrantIds,proto3" json:"matched_grant_ids,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *MatchGrantsResponse) Reset() {
	*x = MatchGrantsResponse{}
	mi := &file_proto_ai_ai_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MatchGrantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MatchGrantsResponse) ProtoMessage() {}

func (x *MatchGrantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MatchGrantsResponse.ProtoReflect.Descriptor instead.
func (*MatchGrantsResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{8}
}

func (x *MatchGrantsResponse) GetMatchedGrantIds() []string {
	if x != nil {
		return x.MatchedGrantIds
	}
	return nil
}

type GetAnalysisHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnalysisHistoryRequest) Reset() {
	*x = GetAnalysisHistoryRequest{}
	mi := &file_proto_ai_ai_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalysisHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalysisHistoryRequest) ProtoMessage() {}

func (x *GetAnalysisHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalysisHistoryRequest.ProtoReflect.Descriptor instead.
func (*GetAnalysisHistoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{9}
}

func (x *GetAnalysisHistoryRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetAnalysisHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	AnalysisIds   []string               `protobuf:"bytes,1,rep,name=analysis_ids,json=analysisIds,proto3" json:"analysis_ids,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAnalysisHistoryResponse) Reset() {
	*x = GetAnalysisHistoryResponse{}
	mi := &file_proto_ai_ai_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAnalysisHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAnalysisHistoryResponse) ProtoMessage() {}

func (x *GetAnalysisHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_ai_ai_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAnalysisHistoryResponse.ProtoReflect.Descriptor instead.
func (*GetAnalysisHistoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_ai_ai_proto_rawDescGZIP(), []int{10}
}

func (x *GetAnalysisHistoryResponse) GetAnalysisIds() []string {
	if x != nil {
		return x.AnalysisIds
	}
	return nil
}

var File_proto_ai_ai_proto protoreflect.FileDescriptor

const file_proto_ai_ai_proto_rawDesc = "" +
	"\n" +
	"\x11proto/ai/ai.proto\x12\x02ai\"\xae\x01\n" +
	"\x1eAnalyzeAdmissionChancesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\runiversity_id\x18\x02 \x01(\tR\funiversityId\x12\x10\n" +
	"\x03gpa\x18\x03 \x01(\x02R\x03gpa\x12\x1b\n" +
	"\tsat_score\x18\x04 \x01(\x05R\bsatScore\x12\x1f\n" +
	"\vielts_score\x18\x05 \x01(\x02R\n" +
	"ieltsScore\"\xdc\x01\n" +
	"\x1fAnalyzeAdmissionChancesResponse\x12>\n" +
	"\x1badmission_chance_percentage\x18\x01 \x01(\x02R\x19admissionChancePercentage\x12\x1d\n" +
	"\n" +
	"weak_areas\x18\x02 \x03(\tR\tweakAreas\x127\n" +
	"\x17improvement_suggestions\x18\x03 \x03(\tR\x16improvementSuggestions\x12!\n" +
	"\fgap_analysis\x18\x04 \x01(\tR\vgapAnalysis\"\x9d\x01\n" +
	"\x16GenerateRoadmapRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x120\n" +
	"\x14target_university_id\x18\x02 \x01(\tR\x12targetUniversityId\x128\n" +
	"\x18months_until_application\x18\x03 \x01(\x05R\x16monthsUntilApplication\"@\n" +
	"\x17GenerateRoadmapResponse\x12%\n" +
	"\x05steps\x18\x01 \x03(\v2\x0f.ai.RoadmapStepR\x05steps\"\x84\x01\n" +
	"\vRoadmapStep\x12\x14\n" +
	"\x05title\x18\x01 \x01(\tR\x05title\x12 \n" +
	"\vdescription\x18\x02 \x01(\tR\vdescription\x12!\n" +
	"\fmonth_number\x18\x03 \x01(\x05R\vmonthNumber\x12\x1a\n" +
	"\bcategory\x18\x04 \x01(\tR\bcategory\"\xb7\x01\n" +
	"\x12ReviewEssayRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x1d\n" +
	"\n" +
	"essay_text\x18\x02 \x01(\tR\tessayText\x12'\n" +
	"\x0funiversity_name\x18\x03 \x01(\tR\x0euniversityName\x12!\n" +
	"\fprogram_name\x18\x04 \x01(\tR\vprogramName\x12\x1d\n" +
	"\n" +
	"word_limit\x18\x05 \x01(\x05R\twordLimit\"\xf0\x01\n" +
	"\x13ReviewEssayResponse\x12#\n" +
	"\rgrammar_score\x18\x01 \x01(\x02R\fgrammarScore\x12'\n" +
	"\x0fcoherence_score\x18\x02 \x01(\x02R\x0ecoherenceScore\x12)\n" +
	"\x10uniqueness_score\x18\x03 \x01(\x02R\x0funiquenessScore\x12'\n" +
	"\x0frelevance_score\x18\x04 \x01(\x02R\x0erelevanceScore\x127\n" +
	"\x17improvement_suggestions\x18\x05 \x03(\tR\x16improvementSuggestions\"}\n" +
	"\x12MatchGrantsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x10\n" +
	"\x03gpa\x18\x02 \x01(\x02R\x03gpa\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12\"\n" +
	"\fachievements\x18\x04 \x03(\tR\fachievements\"A\n" +
	"\x13MatchGrantsResponse\x12*\n" +
	"\x11matched_grant_ids\x18\x01 \x03(\tR\x0fmatchedGrantIds\"4\n" +
	"\x19GetAnalysisHistoryRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"?\n" +
	"\x1aGetAnalysisHistoryResponse\x12!\n" +
	"\fanalysis_ids\x18\x01 \x03(\tR\vanalysisIds2\x90\x03\n" +
	"\tAIService\x12b\n" +
	"\x17AnalyzeAdmissionChances\x12\".ai.AnalyzeAdmissionChancesRequest\x1a#.ai.AnalyzeAdmissionChancesResponse\x12J\n" +
	"\x0fGenerateRoadmap\x12\x1a.ai.GenerateRoadmapRequest\x1a\x1b.ai.GenerateRoadmapResponse\x12>\n" +
	"\vReviewEssay\x12\x16.ai.ReviewEssayRequest\x1a\x17.ai.ReviewEssayResponse\x12>\n" +
	"\vMatchGrants\x12\x16.ai.MatchGrantsRequest\x1a\x17.ai.MatchGrantsResponse\x12S\n" +
	"\x12GetAnalysisHistory\x12\x1d.ai.GetAnalysisHistoryRequest\x1a\x1e.ai.GetAnalysisHistoryResponseB\x1fZ\x1dgithub.com/stepup-ai/proto/aib\x06proto3"

var (
	file_proto_ai_ai_proto_rawDescOnce sync.Once
	file_proto_ai_ai_proto_rawDescData []byte
)

func file_proto_ai_ai_proto_rawDescGZIP() []byte {
	file_proto_ai_ai_proto_rawDescOnce.Do(func() {
		file_proto_ai_ai_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_ai_ai_proto_rawDesc), len(file_proto_ai_ai_proto_rawDesc)))
	})
	return file_proto_ai_ai_proto_rawDescData
}

var file_proto_ai_ai_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_proto_ai_ai_proto_goTypes = []any{
	(*AnalyzeAdmissionChancesRequest)(nil),  // 0: ai.AnalyzeAdmissionChancesRequest
	(*AnalyzeAdmissionChancesResponse)(nil), // 1: ai.AnalyzeAdmissionChancesResponse
	(*GenerateRoadmapRequest)(nil),          // 2: ai.GenerateRoadmapRequest
	(*GenerateRoadmapResponse)(nil),         // 3: ai.GenerateRoadmapResponse
	(*RoadmapStep)(nil),                     // 4: ai.RoadmapStep
	(*ReviewEssayRequest)(nil),              // 5: ai.ReviewEssayRequest
	(*ReviewEssayResponse)(nil),             // 6: ai.ReviewEssayResponse
	(*MatchGrantsRequest)(nil),              // 7: ai.MatchGrantsRequest
	(*MatchGrantsResponse)(nil),             // 8: ai.MatchGrantsResponse
	(*GetAnalysisHistoryRequest)(nil),       // 9: ai.GetAnalysisHistoryRequest
	(*GetAnalysisHistoryResponse)(nil),      // 10: ai.GetAnalysisHistoryResponse
}
var file_proto_ai_ai_proto_depIdxs = []int32{
	4,  // 0: ai.GenerateRoadmapResponse.steps:type_name -> ai.RoadmapStep
	0,  // 1: ai.AIService.AnalyzeAdmissionChances:input_type -> ai.AnalyzeAdmissionChancesRequest
	2,  // 2: ai.AIService.GenerateRoadmap:input_type -> ai.GenerateRoadmapRequest
	5,  // 3: ai.AIService.ReviewEssay:input_type -> ai.ReviewEssayRequest
	7,  // 4: ai.AIService.MatchGrants:input_type -> ai.MatchGrantsRequest
	9,  // 5: ai.AIService.GetAnalysisHistory:input_type -> ai.GetAnalysisHistoryRequest
	1,  // 6: ai.AIService.AnalyzeAdmissionChances:output_type -> ai.AnalyzeAdmissionChancesResponse
	3,  // 7: ai.AIService.GenerateRoadmap:output_type -> ai.GenerateRoadmapResponse
	6,  // 8: ai.AIService.ReviewEssay:output_type -> ai.ReviewEssayResponse
	8,  // 9: ai.AIService.MatchGrants:output_type -> ai.MatchGrantsResponse
	10, // 10: ai.AIService.GetAnalysisHistory:output_type -> ai.GetAnalysisHistoryResponse
	6,  // [6:11] is the sub-list for method output_type
	1,  // [1:6] is the sub-list for method input_type
	1,  // [1:1] is the sub-list for extension type_name
	1,  // [1:1] is the sub-list for extension extendee
	0,  // [0:1] is the sub-list for field type_name
}

func init() { file_proto_ai_ai_proto_init() }
func file_proto_ai_ai_proto_init() {
	if File_proto_ai_ai_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_ai_ai_proto_rawDesc), len(file_proto_ai_ai_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_ai_ai_proto_goTypes,
		DependencyIndexes: file_proto_ai_ai_proto_depIdxs,
		MessageInfos:      file_proto_ai_ai_proto_msgTypes,
	}.Build()
	File_proto_ai_ai_proto = out.File
	file_proto_ai_ai_proto_goTypes = nil
	file_proto_ai_ai_proto_depIdxs = nil
}
