// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/ai/ai.proto

package ai

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	AIService_AnalyzeAdmissionChances_FullMethodName    = "/ai.AIService/AnalyzeAdmissionChances"
	AIService_GenerateRoadmap_FullMethodName            = "/ai.AIService/GenerateRoadmap"
	AIService_ReviewEssay_FullMethodName                = "/ai.AIService/ReviewEssay"
	AIService_MatchGrants_FullMethodName                = "/ai.AIService/MatchGrants"
	AIService_GetAnalysisHistory_FullMethodName         = "/ai.AIService/GetAnalysisHistory"
	AIService_GetRoadmapByUserID_FullMethodName         = "/ai.AIService/GetRoadmapByUserID"
	AIService_GetEssayReviewsByUserID_FullMethodName    = "/ai.AIService/GetEssayReviewsByUserID"
	AIService_GetEssayReviewByID_FullMethodName         = "/ai.AIService/GetEssayReviewByID"
	AIService_DeleteAnalysis_FullMethodName             = "/ai.AIService/DeleteAnalysis"
	AIService_CompareUniversities_FullMethodName        = "/ai.AIService/CompareUniversities"
	AIService_GetRecommendedUniversities_FullMethodName = "/ai.AIService/GetRecommendedUniversities"
	AIService_GetAdmissionAnalysisByID_FullMethodName   = "/ai.AIService/GetAdmissionAnalysisByID"
)

// AIServiceClient is the client API for AIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type AIServiceClient interface {
	AnalyzeAdmissionChances(ctx context.Context, in *AnalyzeAdmissionChancesRequest, opts ...grpc.CallOption) (*AnalyzeAdmissionChancesResponse, error)
	GenerateRoadmap(ctx context.Context, in *GenerateRoadmapRequest, opts ...grpc.CallOption) (*GenerateRoadmapResponse, error)
	ReviewEssay(ctx context.Context, in *ReviewEssayRequest, opts ...grpc.CallOption) (*ReviewEssayResponse, error)
	MatchGrants(ctx context.Context, in *MatchGrantsRequest, opts ...grpc.CallOption) (*MatchGrantsResponse, error)
	GetAnalysisHistory(ctx context.Context, in *GetAnalysisHistoryRequest, opts ...grpc.CallOption) (*GetAnalysisHistoryResponse, error)
	GetRoadmapByUserID(ctx context.Context, in *GetRoadmapByUserIDRequest, opts ...grpc.CallOption) (*GetRoadmapByUserIDResponse, error)
	GetEssayReviewsByUserID(ctx context.Context, in *GetEssayReviewsByUserIDRequest, opts ...grpc.CallOption) (*GetEssayReviewsByUserIDResponse, error)
	GetEssayReviewByID(ctx context.Context, in *GetEssayReviewByIDRequest, opts ...grpc.CallOption) (*GetEssayReviewByIDResponse, error)
	DeleteAnalysis(ctx context.Context, in *DeleteAnalysisRequest, opts ...grpc.CallOption) (*DeleteAnalysisResponse, error)
	CompareUniversities(ctx context.Context, in *CompareUniversitiesRequest, opts ...grpc.CallOption) (*CompareUniversitiesResponse, error)
	GetRecommendedUniversities(ctx context.Context, in *GetRecommendedUniversitiesRequest, opts ...grpc.CallOption) (*GetRecommendedUniversitiesResponse, error)
	GetAdmissionAnalysisByID(ctx context.Context, in *GetAdmissionAnalysisByIDRequest, opts ...grpc.CallOption) (*GetAdmissionAnalysisByIDResponse, error)
}

type aIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewAIServiceClient(cc grpc.ClientConnInterface) AIServiceClient {
	return &aIServiceClient{cc}
}

func (c *aIServiceClient) AnalyzeAdmissionChances(ctx context.Context, in *AnalyzeAdmissionChancesRequest, opts ...grpc.CallOption) (*AnalyzeAdmissionChancesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(AnalyzeAdmissionChancesResponse)
	err := c.cc.Invoke(ctx, AIService_AnalyzeAdmissionChances_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) GenerateRoadmap(ctx context.Context, in *GenerateRoadmapRequest, opts ...grpc.CallOption) (*GenerateRoadmapResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateRoadmapResponse)
	err := c.cc.Invoke(ctx, AIService_GenerateRoadmap_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) ReviewEssay(ctx context.Context, in *ReviewEssayRequest, opts ...grpc.CallOption) (*ReviewEssayResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReviewEssayResponse)
	err := c.cc.Invoke(ctx, AIService_ReviewEssay_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) MatchGrants(ctx context.Context, in *MatchGrantsRequest, opts ...grpc.CallOption) (*MatchGrantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(MatchGrantsResponse)
	err := c.cc.Invoke(ctx, AIService_MatchGrants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) GetAnalysisHistory(ctx context.Context, in *GetAnalysisHistoryRequest, opts ...grpc.CallOption) (*GetAnalysisHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAnalysisHistoryResponse)
	err := c.cc.Invoke(ctx, AIService_GetAnalysisHistory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) GetRoadmapByUserID(ctx context.Context, in *GetRoadmapByUserIDRequest, opts ...grpc.CallOption) (*GetRoadmapByUserIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRoadmapByUserIDResponse)
	err := c.cc.Invoke(ctx, AIService_GetRoadmapByUserID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) GetEssayReviewsByUserID(ctx context.Context, in *GetEssayReviewsByUserIDRequest, opts ...grpc.CallOption) (*GetEssayReviewsByUserIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEssayReviewsByUserIDResponse)
	err := c.cc.Invoke(ctx, AIService_GetEssayReviewsByUserID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) GetEssayReviewByID(ctx context.Context, in *GetEssayReviewByIDRequest, opts ...grpc.CallOption) (*GetEssayReviewByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetEssayReviewByIDResponse)
	err := c.cc.Invoke(ctx, AIService_GetEssayReviewByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) DeleteAnalysis(ctx context.Context, in *DeleteAnalysisRequest, opts ...grpc.CallOption) (*DeleteAnalysisResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteAnalysisResponse)
	err := c.cc.Invoke(ctx, AIService_DeleteAnalysis_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) CompareUniversities(ctx context.Context, in *CompareUniversitiesRequest, opts ...grpc.CallOption) (*CompareUniversitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CompareUniversitiesResponse)
	err := c.cc.Invoke(ctx, AIService_CompareUniversities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) GetRecommendedUniversities(ctx context.Context, in *GetRecommendedUniversitiesRequest, opts ...grpc.CallOption) (*GetRecommendedUniversitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRecommendedUniversitiesResponse)
	err := c.cc.Invoke(ctx, AIService_GetRecommendedUniversities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *aIServiceClient) GetAdmissionAnalysisByID(ctx context.Context, in *GetAdmissionAnalysisByIDRequest, opts ...grpc.CallOption) (*GetAdmissionAnalysisByIDResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetAdmissionAnalysisByIDResponse)
	err := c.cc.Invoke(ctx, AIService_GetAdmissionAnalysisByID_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// AIServiceServer is the server API for AIService service.
// All implementations must embed UnimplementedAIServiceServer
// for forward compatibility.
type AIServiceServer interface {
	AnalyzeAdmissionChances(context.Context, *AnalyzeAdmissionChancesRequest) (*AnalyzeAdmissionChancesResponse, error)
	GenerateRoadmap(context.Context, *GenerateRoadmapRequest) (*GenerateRoadmapResponse, error)
	ReviewEssay(context.Context, *ReviewEssayRequest) (*ReviewEssayResponse, error)
	MatchGrants(context.Context, *MatchGrantsRequest) (*MatchGrantsResponse, error)
	GetAnalysisHistory(context.Context, *GetAnalysisHistoryRequest) (*GetAnalysisHistoryResponse, error)
	GetRoadmapByUserID(context.Context, *GetRoadmapByUserIDRequest) (*GetRoadmapByUserIDResponse, error)
	GetEssayReviewsByUserID(context.Context, *GetEssayReviewsByUserIDRequest) (*GetEssayReviewsByUserIDResponse, error)
	GetEssayReviewByID(context.Context, *GetEssayReviewByIDRequest) (*GetEssayReviewByIDResponse, error)
	DeleteAnalysis(context.Context, *DeleteAnalysisRequest) (*DeleteAnalysisResponse, error)
	CompareUniversities(context.Context, *CompareUniversitiesRequest) (*CompareUniversitiesResponse, error)
	GetRecommendedUniversities(context.Context, *GetRecommendedUniversitiesRequest) (*GetRecommendedUniversitiesResponse, error)
	GetAdmissionAnalysisByID(context.Context, *GetAdmissionAnalysisByIDRequest) (*GetAdmissionAnalysisByIDResponse, error)
	mustEmbedUnimplementedAIServiceServer()
}

// UnimplementedAIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedAIServiceServer struct{}

func (UnimplementedAIServiceServer) AnalyzeAdmissionChances(context.Context, *AnalyzeAdmissionChancesRequest) (*AnalyzeAdmissionChancesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method AnalyzeAdmissionChances not implemented")
}
func (UnimplementedAIServiceServer) GenerateRoadmap(context.Context, *GenerateRoadmapRequest) (*GenerateRoadmapResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GenerateRoadmap not implemented")
}
func (UnimplementedAIServiceServer) ReviewEssay(context.Context, *ReviewEssayRequest) (*ReviewEssayResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReviewEssay not implemented")
}
func (UnimplementedAIServiceServer) MatchGrants(context.Context, *MatchGrantsRequest) (*MatchGrantsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method MatchGrants not implemented")
}
func (UnimplementedAIServiceServer) GetAnalysisHistory(context.Context, *GetAnalysisHistoryRequest) (*GetAnalysisHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAnalysisHistory not implemented")
}
func (UnimplementedAIServiceServer) GetRoadmapByUserID(context.Context, *GetRoadmapByUserIDRequest) (*GetRoadmapByUserIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRoadmapByUserID not implemented")
}
func (UnimplementedAIServiceServer) GetEssayReviewsByUserID(context.Context, *GetEssayReviewsByUserIDRequest) (*GetEssayReviewsByUserIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEssayReviewsByUserID not implemented")
}
func (UnimplementedAIServiceServer) GetEssayReviewByID(context.Context, *GetEssayReviewByIDRequest) (*GetEssayReviewByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetEssayReviewByID not implemented")
}
func (UnimplementedAIServiceServer) DeleteAnalysis(context.Context, *DeleteAnalysisRequest) (*DeleteAnalysisResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DeleteAnalysis not implemented")
}
func (UnimplementedAIServiceServer) CompareUniversities(context.Context, *CompareUniversitiesRequest) (*CompareUniversitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CompareUniversities not implemented")
}
func (UnimplementedAIServiceServer) GetRecommendedUniversities(context.Context, *GetRecommendedUniversitiesRequest) (*GetRecommendedUniversitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRecommendedUniversities not implemented")
}
func (UnimplementedAIServiceServer) GetAdmissionAnalysisByID(context.Context, *GetAdmissionAnalysisByIDRequest) (*GetAdmissionAnalysisByIDResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetAdmissionAnalysisByID not implemented")
}
func (UnimplementedAIServiceServer) mustEmbedUnimplementedAIServiceServer() {}
func (UnimplementedAIServiceServer) testEmbeddedByValue()                   {}

// UnsafeAIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to AIServiceServer will
// result in compilation errors.
type UnsafeAIServiceServer interface {
	mustEmbedUnimplementedAIServiceServer()
}

func RegisterAIServiceServer(s grpc.ServiceRegistrar, srv AIServiceServer) {
	// If the following call panics, it indicates UnimplementedAIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&AIService_ServiceDesc, srv)
}

func _AIService_AnalyzeAdmissionChances_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AnalyzeAdmissionChancesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).AnalyzeAdmissionChances(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_AnalyzeAdmissionChances_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).AnalyzeAdmissionChances(ctx, req.(*AnalyzeAdmissionChancesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_GenerateRoadmap_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateRoadmapRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).GenerateRoadmap(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_GenerateRoadmap_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).GenerateRoadmap(ctx, req.(*GenerateRoadmapRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_ReviewEssay_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReviewEssayRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).ReviewEssay(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_ReviewEssay_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).ReviewEssay(ctx, req.(*ReviewEssayRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_MatchGrants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(MatchGrantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).MatchGrants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_MatchGrants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).MatchGrants(ctx, req.(*MatchGrantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_GetAnalysisHistory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAnalysisHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).GetAnalysisHistory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_GetAnalysisHistory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).GetAnalysisHistory(ctx, req.(*GetAnalysisHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_GetRoadmapByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRoadmapByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).GetRoadmapByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_GetRoadmapByUserID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).GetRoadmapByUserID(ctx, req.(*GetRoadmapByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_GetEssayReviewsByUserID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEssayReviewsByUserIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).GetEssayReviewsByUserID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_GetEssayReviewsByUserID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).GetEssayReviewsByUserID(ctx, req.(*GetEssayReviewsByUserIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_GetEssayReviewByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetEssayReviewByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).GetEssayReviewByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_GetEssayReviewByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).GetEssayReviewByID(ctx, req.(*GetEssayReviewByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_DeleteAnalysis_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteAnalysisRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).DeleteAnalysis(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_DeleteAnalysis_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).DeleteAnalysis(ctx, req.(*DeleteAnalysisRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_CompareUniversities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CompareUniversitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).CompareUniversities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_CompareUniversities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).CompareUniversities(ctx, req.(*CompareUniversitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_GetRecommendedUniversities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRecommendedUniversitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).GetRecommendedUniversities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_GetRecommendedUniversities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).GetRecommendedUniversities(ctx, req.(*GetRecommendedUniversitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _AIService_GetAdmissionAnalysisByID_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetAdmissionAnalysisByIDRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(AIServiceServer).GetAdmissionAnalysisByID(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: AIService_GetAdmissionAnalysisByID_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(AIServiceServer).GetAdmissionAnalysisByID(ctx, req.(*GetAdmissionAnalysisByIDRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// AIService_ServiceDesc is the grpc.ServiceDesc for AIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var AIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ai.AIService",
	HandlerType: (*AIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "AnalyzeAdmissionChances",
			Handler:    _AIService_AnalyzeAdmissionChances_Handler,
		},
		{
			MethodName: "GenerateRoadmap",
			Handler:    _AIService_GenerateRoadmap_Handler,
		},
		{
			MethodName: "ReviewEssay",
			Handler:    _AIService_ReviewEssay_Handler,
		},
		{
			MethodName: "MatchGrants",
			Handler:    _AIService_MatchGrants_Handler,
		},
		{
			MethodName: "GetAnalysisHistory",
			Handler:    _AIService_GetAnalysisHistory_Handler,
		},
		{
			MethodName: "GetRoadmapByUserID",
			Handler:    _AIService_GetRoadmapByUserID_Handler,
		},
		{
			MethodName: "GetEssayReviewsByUserID",
			Handler:    _AIService_GetEssayReviewsByUserID_Handler,
		},
		{
			MethodName: "GetEssayReviewByID",
			Handler:    _AIService_GetEssayReviewByID_Handler,
		},
		{
			MethodName: "DeleteAnalysis",
			Handler:    _AIService_DeleteAnalysis_Handler,
		},
		{
			MethodName: "CompareUniversities",
			Handler:    _AIService_CompareUniversities_Handler,
		},
		{
			MethodName: "GetRecommendedUniversities",
			Handler:    _AIService_GetRecommendedUniversities_Handler,
		},
		{
			MethodName: "GetAdmissionAnalysisByID",
			Handler:    _AIService_GetAdmissionAnalysisByID_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/ai/ai.proto",
}
