// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: proto/university/university.proto

package university

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SearchUniversitiesRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	Country           string                 `protobuf:"bytes,1,opt,name=country,proto3" json:"country,omitempty"`
	Type              string                 `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	MinAcceptanceRate float32                `protobuf:"fixed32,3,opt,name=min_acceptance_rate,json=minAcceptanceRate,proto3" json:"min_acceptance_rate,omitempty"`
	MaxAcceptanceRate float32                `protobuf:"fixed32,4,opt,name=max_acceptance_rate,json=maxAcceptanceRate,proto3" json:"max_acceptance_rate,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *SearchUniversitiesRequest) Reset() {
	*x = SearchUniversitiesRequest{}
	mi := &file_proto_university_university_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUniversitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUniversitiesRequest) ProtoMessage() {}

func (x *SearchUniversitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_university_university_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUniversitiesRequest.ProtoReflect.Descriptor instead.
func (*SearchUniversitiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_university_university_proto_rawDescGZIP(), []int{0}
}

func (x *SearchUniversitiesRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *SearchUniversitiesRequest) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *SearchUniversitiesRequest) GetMinAcceptanceRate() float32 {
	if x != nil {
		return x.MinAcceptanceRate
	}
	return 0
}

func (x *SearchUniversitiesRequest) GetMaxAcceptanceRate() float32 {
	if x != nil {
		return x.MaxAcceptanceRate
	}
	return 0
}

type SearchUniversitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Universities  []*University          `protobuf:"bytes,1,rep,name=universities,proto3" json:"universities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchUniversitiesResponse) Reset() {
	*x = SearchUniversitiesResponse{}
	mi := &file_proto_university_university_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchUniversitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchUniversitiesResponse) ProtoMessage() {}

func (x *SearchUniversitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_university_university_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchUniversitiesResponse.ProtoReflect.Descriptor instead.
func (*SearchUniversitiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_university_university_proto_rawDescGZIP(), []int{1}
}

func (x *SearchUniversitiesResponse) GetUniversities() []*University {
	if x != nil {
		return x.Universities
	}
	return nil
}

type University struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name           string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Country        string                 `protobuf:"bytes,3,opt,name=country,proto3" json:"country,omitempty"`
	AcceptanceRate float32                `protobuf:"fixed32,4,opt,name=acceptance_rate,json=acceptanceRate,proto3" json:"acceptance_rate,omitempty"`
	Type           string                 `protobuf:"bytes,5,opt,name=type,proto3" json:"type,omitempty"`
	Category       string                 `protobuf:"bytes,6,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *University) Reset() {
	*x = University{}
	mi := &file_proto_university_university_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *University) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*University) ProtoMessage() {}

func (x *University) ProtoReflect() protoreflect.Message {
	mi := &file_proto_university_university_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use University.ProtoReflect.Descriptor instead.
func (*University) Descriptor() ([]byte, []int) {
	return file_proto_university_university_proto_rawDescGZIP(), []int{2}
}

func (x *University) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *University) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *University) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *University) GetAcceptanceRate() float32 {
	if x != nil {
		return x.AcceptanceRate
	}
	return 0
}

func (x *University) GetType() string {
	if x != nil {
		return x.Type
	}
	return ""
}

func (x *University) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type GetUniversityDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UniversityId  string                 `protobuf:"bytes,1,opt,name=university_id,json=universityId,proto3" json:"university_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUniversityDetailsRequest) Reset() {
	*x = GetUniversityDetailsRequest{}
	mi := &file_proto_university_university_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUniversityDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUniversityDetailsRequest) ProtoMessage() {}

func (x *GetUniversityDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_university_university_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUniversityDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetUniversityDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_university_university_proto_rawDescGZIP(), []int{3}
}

func (x *GetUniversityDetailsRequest) GetUniversityId() string {
	if x != nil {
		return x.UniversityId
	}
	return ""
}

type GetUniversityDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	University    *University            `protobuf:"bytes,1,opt,name=university,proto3" json:"university,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUniversityDetailsResponse) Reset() {
	*x = GetUniversityDetailsResponse{}
	mi := &file_proto_university_university_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUniversityDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUniversityDetailsResponse) ProtoMessage() {}

func (x *GetUniversityDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_university_university_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUniversityDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetUniversityDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_university_university_proto_rawDescGZIP(), []int{4}
}

func (x *GetUniversityDetailsResponse) GetUniversity() *University {
	if x != nil {
		return x.University
	}
	return nil
}

type SaveUniversityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UniversityId  string                 `protobuf:"bytes,2,opt,name=university_id,json=universityId,proto3" json:"university_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveUniversityRequest) Reset() {
	*x = SaveUniversityRequest{}
	mi := &file_proto_university_university_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveUniversityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveUniversityRequest) ProtoMessage() {}

func (x *SaveUniversityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_university_university_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveUniversityRequest.ProtoReflect.Descriptor instead.
func (*SaveUniversityRequest) Descriptor() ([]byte, []int) {
	return file_proto_university_university_proto_rawDescGZIP(), []int{5}
}

func (x *SaveUniversityRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SaveUniversityRequest) GetUniversityId() string {
	if x != nil {
		return x.UniversityId
	}
	return ""
}

type SaveUniversityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveUniversityResponse) Reset() {
	*x = SaveUniversityResponse{}
	mi := &file_proto_university_university_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveUniversityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveUniversityResponse) ProtoMessage() {}

func (x *SaveUniversityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_university_university_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveUniversityResponse.ProtoReflect.Descriptor instead.
func (*SaveUniversityResponse) Descriptor() ([]byte, []int) {
	return file_proto_university_university_proto_rawDescGZIP(), []int{6}
}

func (x *SaveUniversityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetSavedUniversitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSavedUniversitiesRequest) Reset() {
	*x = GetSavedUniversitiesRequest{}
	mi := &file_proto_university_university_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSavedUniversitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSavedUniversitiesRequest) ProtoMessage() {}

func (x *GetSavedUniversitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_university_university_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSavedUniversitiesRequest.ProtoReflect.Descriptor instead.
func (*GetSavedUniversitiesRequest) Descriptor() ([]byte, []int) {
	return file_proto_university_university_proto_rawDescGZIP(), []int{7}
}

func (x *GetSavedUniversitiesRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetSavedUniversitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Universities  []*University          `protobuf:"bytes,1,rep,name=universities,proto3" json:"universities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSavedUniversitiesResponse) Reset() {
	*x = GetSavedUniversitiesResponse{}
	mi := &file_proto_university_university_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSavedUniversitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSavedUniversitiesResponse) ProtoMessage() {}

func (x *GetSavedUniversitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_university_university_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSavedUniversitiesResponse.ProtoReflect.Descriptor instead.
func (*GetSavedUniversitiesResponse) Descriptor() ([]byte, []int) {
	return file_proto_university_university_proto_rawDescGZIP(), []int{8}
}

func (x *GetSavedUniversitiesResponse) GetUniversities() []*University {
	if x != nil {
		return x.Universities
	}
	return nil
}

type SearchGrantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	Country       string                 `protobuf:"bytes,2,opt,name=country,proto3" json:"country,omitempty"`
	Gpa           float32                `protobuf:"fixed32,3,opt,name=gpa,proto3" json:"gpa,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchGrantsRequest) Reset() {
	*x = SearchGrantsRequest{}
	mi := &file_proto_university_university_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchGrantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchGrantsRequest) ProtoMessage() {}

func (x *SearchGrantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_university_university_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchGrantsRequest.ProtoReflect.Descriptor instead.
func (*SearchGrantsRequest) Descriptor() ([]byte, []int) {
	return file_proto_university_university_proto_rawDescGZIP(), []int{9}
}

func (x *SearchGrantsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SearchGrantsRequest) GetCountry() string {
	if x != nil {
		return x.Country
	}
	return ""
}

func (x *SearchGrantsRequest) GetGpa() float32 {
	if x != nil {
		return x.Gpa
	}
	return 0
}

type SearchGrantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grants        []*Grant               `protobuf:"bytes,1,rep,name=grants,proto3" json:"grants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SearchGrantsResponse) Reset() {
	*x = SearchGrantsResponse{}
	mi := &file_proto_university_university_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SearchGrantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SearchGrantsResponse) ProtoMessage() {}

func (x *SearchGrantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_university_university_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SearchGrantsResponse.ProtoReflect.Descriptor instead.
func (*SearchGrantsResponse) Descriptor() ([]byte, []int) {
	return file_proto_university_university_proto_rawDescGZIP(), []int{10}
}

func (x *SearchGrantsResponse) GetGrants() []*Grant {
	if x != nil {
		return x.Grants
	}
	return nil
}

type Grant struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Amount        float32                `protobuf:"fixed32,4,opt,name=amount,proto3" json:"amount,omitempty"`
	Deadline      string                 `protobuf:"bytes,5,opt,name=deadline,proto3" json:"deadline,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Grant) Reset() {
	*x = Grant{}
	mi := &file_proto_university_university_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Grant) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Grant) ProtoMessage() {}

func (x *Grant) ProtoReflect() protoreflect.Message {
	mi := &file_proto_university_university_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Grant.ProtoReflect.Descriptor instead.
func (*Grant) Descriptor() ([]byte, []int) {
	return file_proto_university_university_proto_rawDescGZIP(), []int{11}
}

func (x *Grant) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Grant) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Grant) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Grant) GetAmount() float32 {
	if x != nil {
		return x.Amount
	}
	return 0
}

func (x *Grant) GetDeadline() string {
	if x != nil {
		return x.Deadline
	}
	return ""
}

type SaveGrantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GrantId       string                 `protobuf:"bytes,2,opt,name=grant_id,json=grantId,proto3" json:"grant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveGrantRequest) Reset() {
	*x = SaveGrantRequest{}
	mi := &file_proto_university_university_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveGrantRequest) ProtoMessage() {}

func (x *SaveGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_university_university_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveGrantRequest.ProtoReflect.Descriptor instead.
func (*SaveGrantRequest) Descriptor() ([]byte, []int) {
	return file_proto_university_university_proto_rawDescGZIP(), []int{12}
}

func (x *SaveGrantRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *SaveGrantRequest) GetGrantId() string {
	if x != nil {
		return x.GrantId
	}
	return ""
}

type SaveGrantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SaveGrantResponse) Reset() {
	*x = SaveGrantResponse{}
	mi := &file_proto_university_university_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SaveGrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SaveGrantResponse) ProtoMessage() {}

func (x *SaveGrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_university_university_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SaveGrantResponse.ProtoReflect.Descriptor instead.
func (*SaveGrantResponse) Descriptor() ([]byte, []int) {
	return file_proto_university_university_proto_rawDescGZIP(), []int{13}
}

func (x *SaveGrantResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetSavedGrantsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSavedGrantsRequest) Reset() {
	*x = GetSavedGrantsRequest{}
	mi := &file_proto_university_university_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSavedGrantsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSavedGrantsRequest) ProtoMessage() {}

func (x *GetSavedGrantsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_university_university_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSavedGrantsRequest.ProtoReflect.Descriptor instead.
func (*GetSavedGrantsRequest) Descriptor() ([]byte, []int) {
	return file_proto_university_university_proto_rawDescGZIP(), []int{14}
}

func (x *GetSavedGrantsRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type GetSavedGrantsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grants        []*Grant               `protobuf:"bytes,1,rep,name=grants,proto3" json:"grants,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetSavedGrantsResponse) Reset() {
	*x = GetSavedGrantsResponse{}
	mi := &file_proto_university_university_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetSavedGrantsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetSavedGrantsResponse) ProtoMessage() {}

func (x *GetSavedGrantsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_university_university_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetSavedGrantsResponse.ProtoReflect.Descriptor instead.
func (*GetSavedGrantsResponse) Descriptor() ([]byte, []int) {
	return file_proto_university_university_proto_rawDescGZIP(), []int{15}
}

func (x *GetSavedGrantsResponse) GetGrants() []*Grant {
	if x != nil {
		return x.Grants
	}
	return nil
}

type RemoveSavedUniversityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	UniversityId  string                 `protobuf:"bytes,2,opt,name=university_id,json=universityId,proto3" json:"university_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSavedUniversityRequest) Reset() {
	*x = RemoveSavedUniversityRequest{}
	mi := &file_proto_university_university_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSavedUniversityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSavedUniversityRequest) ProtoMessage() {}

func (x *RemoveSavedUniversityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_university_university_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSavedUniversityRequest.ProtoReflect.Descriptor instead.
func (*RemoveSavedUniversityRequest) Descriptor() ([]byte, []int) {
	return file_proto_university_university_proto_rawDescGZIP(), []int{16}
}

func (x *RemoveSavedUniversityRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveSavedUniversityRequest) GetUniversityId() string {
	if x != nil {
		return x.UniversityId
	}
	return ""
}

type RemoveSavedUniversityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSavedUniversityResponse) Reset() {
	*x = RemoveSavedUniversityResponse{}
	mi := &file_proto_university_university_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSavedUniversityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSavedUniversityResponse) ProtoMessage() {}

func (x *RemoveSavedUniversityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_university_university_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSavedUniversityResponse.ProtoReflect.Descriptor instead.
func (*RemoveSavedUniversityResponse) Descriptor() ([]byte, []int) {
	return file_proto_university_university_proto_rawDescGZIP(), []int{17}
}

func (x *RemoveSavedUniversityResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RemoveSavedGrantRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	GrantId       string                 `protobuf:"bytes,2,opt,name=grant_id,json=grantId,proto3" json:"grant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSavedGrantRequest) Reset() {
	*x = RemoveSavedGrantRequest{}
	mi := &file_proto_university_university_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSavedGrantRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSavedGrantRequest) ProtoMessage() {}

func (x *RemoveSavedGrantRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_university_university_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSavedGrantRequest.ProtoReflect.Descriptor instead.
func (*RemoveSavedGrantRequest) Descriptor() ([]byte, []int) {
	return file_proto_university_university_proto_rawDescGZIP(), []int{18}
}

func (x *RemoveSavedGrantRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *RemoveSavedGrantRequest) GetGrantId() string {
	if x != nil {
		return x.GrantId
	}
	return ""
}

type RemoveSavedGrantResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RemoveSavedGrantResponse) Reset() {
	*x = RemoveSavedGrantResponse{}
	mi := &file_proto_university_university_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RemoveSavedGrantResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RemoveSavedGrantResponse) ProtoMessage() {}

func (x *RemoveSavedGrantResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_university_university_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RemoveSavedGrantResponse.ProtoReflect.Descriptor instead.
func (*RemoveSavedGrantResponse) Descriptor() ([]byte, []int) {
	return file_proto_university_university_proto_rawDescGZIP(), []int{19}
}

func (x *RemoveSavedGrantResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetGrantDetailsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GrantId       string                 `protobuf:"bytes,1,opt,name=grant_id,json=grantId,proto3" json:"grant_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGrantDetailsRequest) Reset() {
	*x = GetGrantDetailsRequest{}
	mi := &file_proto_university_university_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGrantDetailsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGrantDetailsRequest) ProtoMessage() {}

func (x *GetGrantDetailsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_university_university_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGrantDetailsRequest.ProtoReflect.Descriptor instead.
func (*GetGrantDetailsRequest) Descriptor() ([]byte, []int) {
	return file_proto_university_university_proto_rawDescGZIP(), []int{20}
}

func (x *GetGrantDetailsRequest) GetGrantId() string {
	if x != nil {
		return x.GrantId
	}
	return ""
}

type GetGrantDetailsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Grant         *Grant                 `protobuf:"bytes,1,opt,name=grant,proto3" json:"grant,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetGrantDetailsResponse) Reset() {
	*x = GetGrantDetailsResponse{}
	mi := &file_proto_university_university_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetGrantDetailsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetGrantDetailsResponse) ProtoMessage() {}

func (x *GetGrantDetailsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_university_university_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetGrantDetailsResponse.ProtoReflect.Descriptor instead.
func (*GetGrantDetailsResponse) Descriptor() ([]byte, []int) {
	return file_proto_university_university_proto_rawDescGZIP(), []int{21}
}

func (x *GetGrantDetailsResponse) GetGrant() *Grant {
	if x != nil {
		return x.Grant
	}
	return nil
}

type ListUniversitiesByCategoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Category      string                 `protobuf:"bytes,1,opt,name=category,proto3" json:"category,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUniversitiesByCategoryRequest) Reset() {
	*x = ListUniversitiesByCategoryRequest{}
	mi := &file_proto_university_university_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUniversitiesByCategoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUniversitiesByCategoryRequest) ProtoMessage() {}

func (x *ListUniversitiesByCategoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_university_university_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUniversitiesByCategoryRequest.ProtoReflect.Descriptor instead.
func (*ListUniversitiesByCategoryRequest) Descriptor() ([]byte, []int) {
	return file_proto_university_university_proto_rawDescGZIP(), []int{22}
}

func (x *ListUniversitiesByCategoryRequest) GetCategory() string {
	if x != nil {
		return x.Category
	}
	return ""
}

type ListUniversitiesByCategoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Universities  []*University          `protobuf:"bytes,1,rep,name=universities,proto3" json:"universities,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListUniversitiesByCategoryResponse) Reset() {
	*x = ListUniversitiesByCategoryResponse{}
	mi := &file_proto_university_university_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListUniversitiesByCategoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListUniversitiesByCategoryResponse) ProtoMessage() {}

func (x *ListUniversitiesByCategoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_university_university_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListUniversitiesByCategoryResponse.ProtoReflect.Descriptor instead.
func (*ListUniversitiesByCategoryResponse) Descriptor() ([]byte, []int) {
	return file_proto_university_university_proto_rawDescGZIP(), []int{23}
}

func (x *ListUniversitiesByCategoryResponse) GetUniversities() []*University {
	if x != nil {
		return x.Universities
	}
	return nil
}

type GetUniversityStatisticsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUniversityStatisticsRequest) Reset() {
	*x = GetUniversityStatisticsRequest{}
	mi := &file_proto_university_university_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUniversityStatisticsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUniversityStatisticsRequest) ProtoMessage() {}

func (x *GetUniversityStatisticsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_proto_university_university_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUniversityStatisticsRequest.ProtoReflect.Descriptor instead.
func (*GetUniversityStatisticsRequest) Descriptor() ([]byte, []int) {
	return file_proto_university_university_proto_rawDescGZIP(), []int{24}
}

type GetUniversityStatisticsResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	TotalUniversities int32                  `protobuf:"varint,1,opt,name=total_universities,json=totalUniversities,proto3" json:"total_universities,omitempty"`
	TotalReach        int32                  `protobuf:"varint,2,opt,name=total_reach,json=totalReach,proto3" json:"total_reach,omitempty"`
	TotalTarget       int32                  `protobuf:"varint,3,opt,name=total_target,json=totalTarget,proto3" json:"total_target,omitempty"`
	TotalSafety       int32                  `protobuf:"varint,4,opt,name=total_safety,json=totalSafety,proto3" json:"total_safety,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetUniversityStatisticsResponse) Reset() {
	*x = GetUniversityStatisticsResponse{}
	mi := &file_proto_university_university_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUniversityStatisticsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUniversityStatisticsResponse) ProtoMessage() {}

func (x *GetUniversityStatisticsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_proto_university_university_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUniversityStatisticsResponse.ProtoReflect.Descriptor instead.
func (*GetUniversityStatisticsResponse) Descriptor() ([]byte, []int) {
	return file_proto_university_university_proto_rawDescGZIP(), []int{25}
}

func (x *GetUniversityStatisticsResponse) GetTotalUniversities() int32 {
	if x != nil {
		return x.TotalUniversities
	}
	return 0
}

func (x *GetUniversityStatisticsResponse) GetTotalReach() int32 {
	if x != nil {
		return x.TotalReach
	}
	return 0
}

func (x *GetUniversityStatisticsResponse) GetTotalTarget() int32 {
	if x != nil {
		return x.TotalTarget
	}
	return 0
}

func (x *GetUniversityStatisticsResponse) GetTotalSafety() int32 {
	if x != nil {
		return x.TotalSafety
	}
	return 0
}

var File_proto_university_university_proto protoreflect.FileDescriptor

const file_proto_university_university_proto_rawDesc = "" +
	"\n" +
	"!proto/university/university.proto\x12\n" +
	"university\"\xa9\x01\n" +
	"\x19SearchUniversitiesRequest\x12\x18\n" +
	"\acountry\x18\x01 \x01(\tR\acountry\x12\x12\n" +
	"\x04type\x18\x02 \x01(\tR\x04type\x12.\n" +
	"\x13min_acceptance_rate\x18\x03 \x01(\x02R\x11minAcceptanceRate\x12.\n" +
	"\x13max_acceptance_rate\x18\x04 \x01(\x02R\x11maxAcceptanceRate\"X\n" +
	"\x1aSearchUniversitiesResponse\x12:\n" +
	"\funiversities\x18\x01 \x03(\v2\x16.university.UniversityR\funiversities\"\xa3\x01\n" +
	"\n" +
	"University\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x18\n" +
	"\acountry\x18\x03 \x01(\tR\acountry\x12'\n" +
	"\x0facceptance_rate\x18\x04 \x01(\x02R\x0eacceptanceRate\x12\x12\n" +
	"\x04type\x18\x05 \x01(\tR\x04type\x12\x1a\n" +
	"\bcategory\x18\x06 \x01(\tR\bcategory\"B\n" +
	"\x1bGetUniversityDetailsRequest\x12#\n" +
	"\runiversity_id\x18\x01 \x01(\tR\funiversityId\"V\n" +
	"\x1cGetUniversityDetailsResponse\x126\n" +
	"\n" +
	"university\x18\x01 \x01(\v2\x16.university.UniversityR\n" +
	"university\"U\n" +
	"\x15SaveUniversityRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\runiversity_id\x18\x02 \x01(\tR\funiversityId\"2\n" +
	"\x16SaveUniversityResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"6\n" +
	"\x1bGetSavedUniversitiesRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"Z\n" +
	"\x1cGetSavedUniversitiesResponse\x12:\n" +
	"\funiversities\x18\x01 \x03(\v2\x16.university.UniversityR\funiversities\"Z\n" +
	"\x13SearchGrantsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x18\n" +
	"\acountry\x18\x02 \x01(\tR\acountry\x12\x10\n" +
	"\x03gpa\x18\x03 \x01(\x02R\x03gpa\"A\n" +
	"\x14SearchGrantsResponse\x12)\n" +
	"\x06grants\x18\x01 \x03(\v2\x11.university.GrantR\x06grants\"\x81\x01\n" +
	"\x05Grant\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x16\n" +
	"\x06amount\x18\x04 \x01(\x02R\x06amount\x12\x1a\n" +
	"\bdeadline\x18\x05 \x01(\tR\bdeadline\"F\n" +
	"\x10SaveGrantRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bgrant_id\x18\x02 \x01(\tR\agrantId\"-\n" +
	"\x11SaveGrantResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"0\n" +
	"\x15GetSavedGrantsRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"C\n" +
	"\x16GetSavedGrantsResponse\x12)\n" +
	"\x06grants\x18\x01 \x03(\v2\x11.university.GrantR\x06grants\"\\\n" +
	"\x1cRemoveSavedUniversityRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12#\n" +
	"\runiversity_id\x18\x02 \x01(\tR\funiversityId\"9\n" +
	"\x1dRemoveSavedUniversityResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"M\n" +
	"\x17RemoveSavedGrantRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12\x19\n" +
	"\bgrant_id\x18\x02 \x01(\tR\agrantId\"4\n" +
	"\x18RemoveSavedGrantResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"3\n" +
	"\x16GetGrantDetailsRequest\x12\x19\n" +
	"\bgrant_id\x18\x01 \x01(\tR\agrantId\"B\n" +
	"\x17GetGrantDetailsResponse\x12'\n" +
	"\x05grant\x18\x01 \x01(\v2\x11.university.GrantR\x05grant\"?\n" +
	"!ListUniversitiesByCategoryRequest\x12\x1a\n" +
	"\bcategory\x18\x01 \x01(\tR\bcategory\"`\n" +
	"\"ListUniversitiesByCategoryResponse\x12:\n" +
	"\funiversities\x18\x01 \x03(\v2\x16.university.UniversityR\funiversities\" \n" +
	"\x1eGetUniversityStatisticsRequest\"\xb7\x01\n" +
	"\x1fGetUniversityStatisticsResponse\x12-\n" +
	"\x12total_universities\x18\x01 \x01(\x05R\x11totalUniversities\x12\x1f\n" +
	"\vtotal_reach\x18\x02 \x01(\x05R\n" +
	"totalReach\x12!\n" +
	"\ftotal_target\x18\x03 \x01(\x05R\vtotalTarget\x12!\n" +
	"\ftotal_safety\x18\x04 \x01(\x05R\vtotalSafety2\xb7\t\n" +
	"\x11UniversityService\x12c\n" +
	"\x12SearchUniversities\x12%.university.SearchUniversitiesRequest\x1a&.university.SearchUniversitiesResponse\x12i\n" +
	"\x14GetUniversityDetails\x12'.university.GetUniversityDetailsRequest\x1a(.university.GetUniversityDetailsResponse\x12W\n" +
	"\x0eSaveUniversity\x12!.university.SaveUniversityRequest\x1a\".university.SaveUniversityResponse\x12i\n" +
	"\x14GetSavedUniversities\x12'.university.GetSavedUniversitiesRequest\x1a(.university.GetSavedUniversitiesResponse\x12Q\n" +
	"\fSearchGrants\x12\x1f.university.SearchGrantsRequest\x1a .university.SearchGrantsResponse\x12H\n" +
	"\tSaveGrant\x12\x1c.university.SaveGrantRequest\x1a\x1d.university.SaveGrantResponse\x12W\n" +
	"\x0eGetSavedGrants\x12!.university.GetSavedGrantsRequest\x1a\".university.GetSavedGrantsResponse\x12l\n" +
	"\x15RemoveSavedUniversity\x12(.university.RemoveSavedUniversityRequest\x1a).university.RemoveSavedUniversityResponse\x12]\n" +
	"\x10RemoveSavedGrant\x12#.university.RemoveSavedGrantRequest\x1a$.university.RemoveSavedGrantResponse\x12Z\n" +
	"\x0fGetGrantDetails\x12\".university.GetGrantDetailsRequest\x1a#.university.GetGrantDetailsResponse\x12{\n" +
	"\x1aListUniversitiesByCategory\x12-.university.ListUniversitiesByCategoryRequest\x1a..university.ListUniversitiesByCategoryResponse\x12r\n" +
	"\x17GetUniversityStatistics\x12*.university.GetUniversityStatisticsRequest\x1a+.university.GetUniversityStatisticsResponseB'Z%github.com/stepup-ai/proto/universityb\x06proto3"

var (
	file_proto_university_university_proto_rawDescOnce sync.Once
	file_proto_university_university_proto_rawDescData []byte
)

func file_proto_university_university_proto_rawDescGZIP() []byte {
	file_proto_university_university_proto_rawDescOnce.Do(func() {
		file_proto_university_university_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_proto_university_university_proto_rawDesc), len(file_proto_university_university_proto_rawDesc)))
	})
	return file_proto_university_university_proto_rawDescData
}

var file_proto_university_university_proto_msgTypes = make([]protoimpl.MessageInfo, 26)
var file_proto_university_university_proto_goTypes = []any{
	(*SearchUniversitiesRequest)(nil),          // 0: university.SearchUniversitiesRequest
	(*SearchUniversitiesResponse)(nil),         // 1: university.SearchUniversitiesResponse
	(*University)(nil),                         // 2: university.University
	(*GetUniversityDetailsRequest)(nil),        // 3: university.GetUniversityDetailsRequest
	(*GetUniversityDetailsResponse)(nil),       // 4: university.GetUniversityDetailsResponse
	(*SaveUniversityRequest)(nil),              // 5: university.SaveUniversityRequest
	(*SaveUniversityResponse)(nil),             // 6: university.SaveUniversityResponse
	(*GetSavedUniversitiesRequest)(nil),        // 7: university.GetSavedUniversitiesRequest
	(*GetSavedUniversitiesResponse)(nil),       // 8: university.GetSavedUniversitiesResponse
	(*SearchGrantsRequest)(nil),                // 9: university.SearchGrantsRequest
	(*SearchGrantsResponse)(nil),               // 10: university.SearchGrantsResponse
	(*Grant)(nil),                              // 11: university.Grant
	(*SaveGrantRequest)(nil),                   // 12: university.SaveGrantRequest
	(*SaveGrantResponse)(nil),                  // 13: university.SaveGrantResponse
	(*GetSavedGrantsRequest)(nil),              // 14: university.GetSavedGrantsRequest
	(*GetSavedGrantsResponse)(nil),             // 15: university.GetSavedGrantsResponse
	(*RemoveSavedUniversityRequest)(nil),       // 16: university.RemoveSavedUniversityRequest
	(*RemoveSavedUniversityResponse)(nil),      // 17: university.RemoveSavedUniversityResponse
	(*RemoveSavedGrantRequest)(nil),            // 18: university.RemoveSavedGrantRequest
	(*RemoveSavedGrantResponse)(nil),           // 19: university.RemoveSavedGrantResponse
	(*GetGrantDetailsRequest)(nil),             // 20: university.GetGrantDetailsRequest
	(*GetGrantDetailsResponse)(nil),            // 21: university.GetGrantDetailsResponse
	(*ListUniversitiesByCategoryRequest)(nil),  // 22: university.ListUniversitiesByCategoryRequest
	(*ListUniversitiesByCategoryResponse)(nil), // 23: university.ListUniversitiesByCategoryResponse
	(*GetUniversityStatisticsRequest)(nil),     // 24: university.GetUniversityStatisticsRequest
	(*GetUniversityStatisticsResponse)(nil),    // 25: university.GetUniversityStatisticsResponse
}
var file_proto_university_university_proto_depIdxs = []int32{
	2,  // 0: university.SearchUniversitiesResponse.universities:type_name -> university.University
	2,  // 1: university.GetUniversityDetailsResponse.university:type_name -> university.University
	2,  // 2: university.GetSavedUniversitiesResponse.universities:type_name -> university.University
	11, // 3: university.SearchGrantsResponse.grants:type_name -> university.Grant
	11, // 4: university.GetSavedGrantsResponse.grants:type_name -> university.Grant
	11, // 5: university.GetGrantDetailsResponse.grant:type_name -> university.Grant
	2,  // 6: university.ListUniversitiesByCategoryResponse.universities:type_name -> university.University
	0,  // 7: university.UniversityService.SearchUniversities:input_type -> university.SearchUniversitiesRequest
	3,  // 8: university.UniversityService.GetUniversityDetails:input_type -> university.GetUniversityDetailsRequest
	5,  // 9: university.UniversityService.SaveUniversity:input_type -> university.SaveUniversityRequest
	7,  // 10: university.UniversityService.GetSavedUniversities:input_type -> university.GetSavedUniversitiesRequest
	9,  // 11: university.UniversityService.SearchGrants:input_type -> university.SearchGrantsRequest
	12, // 12: university.UniversityService.SaveGrant:input_type -> university.SaveGrantRequest
	14, // 13: university.UniversityService.GetSavedGrants:input_type -> university.GetSavedGrantsRequest
	16, // 14: university.UniversityService.RemoveSavedUniversity:input_type -> university.RemoveSavedUniversityRequest
	18, // 15: university.UniversityService.RemoveSavedGrant:input_type -> university.RemoveSavedGrantRequest
	20, // 16: university.UniversityService.GetGrantDetails:input_type -> university.GetGrantDetailsRequest
	22, // 17: university.UniversityService.ListUniversitiesByCategory:input_type -> university.ListUniversitiesByCategoryRequest
	24, // 18: university.UniversityService.GetUniversityStatistics:input_type -> university.GetUniversityStatisticsRequest
	1,  // 19: university.UniversityService.SearchUniversities:output_type -> university.SearchUniversitiesResponse
	4,  // 20: university.UniversityService.GetUniversityDetails:output_type -> university.GetUniversityDetailsResponse
	6,  // 21: university.UniversityService.SaveUniversity:output_type -> university.SaveUniversityResponse
	8,  // 22: university.UniversityService.GetSavedUniversities:output_type -> university.GetSavedUniversitiesResponse
	10, // 23: university.UniversityService.SearchGrants:output_type -> university.SearchGrantsResponse
	13, // 24: university.UniversityService.SaveGrant:output_type -> university.SaveGrantResponse
	15, // 25: university.UniversityService.GetSavedGrants:output_type -> university.GetSavedGrantsResponse
	17, // 26: university.UniversityService.RemoveSavedUniversity:output_type -> university.RemoveSavedUniversityResponse
	19, // 27: university.UniversityService.RemoveSavedGrant:output_type -> university.RemoveSavedGrantResponse
	21, // 28: university.UniversityService.GetGrantDetails:output_type -> university.GetGrantDetailsResponse
	23, // 29: university.UniversityService.ListUniversitiesByCategory:output_type -> university.ListUniversitiesByCategoryResponse
	25, // 30: university.UniversityService.GetUniversityStatistics:output_type -> university.GetUniversityStatisticsResponse
	19, // [19:31] is the sub-list for method output_type
	7,  // [7:19] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_proto_university_university_proto_init() }
func file_proto_university_university_proto_init() {
	if File_proto_university_university_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_proto_university_university_proto_rawDesc), len(file_proto_university_university_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   26,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_proto_university_university_proto_goTypes,
		DependencyIndexes: file_proto_university_university_proto_depIdxs,
		MessageInfos:      file_proto_university_university_proto_msgTypes,
	}.Build()
	File_proto_university_university_proto = out.File
	file_proto_university_university_proto_goTypes = nil
	file_proto_university_university_proto_depIdxs = nil
}
