// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             v7.34.1
// source: proto/university/university.proto

package university

import (
	context "context"

	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	UniversityService_SearchUniversities_FullMethodName         = "/university.UniversityService/SearchUniversities"
	UniversityService_GetUniversityDetails_FullMethodName       = "/university.UniversityService/GetUniversityDetails"
	UniversityService_SaveUniversity_FullMethodName             = "/university.UniversityService/SaveUniversity"
	UniversityService_GetSavedUniversities_FullMethodName       = "/university.UniversityService/GetSavedUniversities"
	UniversityService_SearchGrants_FullMethodName               = "/university.UniversityService/SearchGrants"
	UniversityService_SaveGrant_FullMethodName                  = "/university.UniversityService/SaveGrant"
	UniversityService_GetSavedGrants_FullMethodName             = "/university.UniversityService/GetSavedGrants"
	UniversityService_RemoveSavedUniversity_FullMethodName      = "/university.UniversityService/RemoveSavedUniversity"
	UniversityService_RemoveSavedGrant_FullMethodName           = "/university.UniversityService/RemoveSavedGrant"
	UniversityService_GetGrantDetails_FullMethodName            = "/university.UniversityService/GetGrantDetails"
	UniversityService_ListUniversitiesByCategory_FullMethodName = "/university.UniversityService/ListUniversitiesByCategory"
	UniversityService_GetUniversityStatistics_FullMethodName    = "/university.UniversityService/GetUniversityStatistics"
)

// UniversityServiceClient is the client API for UniversityService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UniversityServiceClient interface {
	SearchUniversities(ctx context.Context, in *SearchUniversitiesRequest, opts ...grpc.CallOption) (*SearchUniversitiesResponse, error)
	GetUniversityDetails(ctx context.Context, in *GetUniversityDetailsRequest, opts ...grpc.CallOption) (*GetUniversityDetailsResponse, error)
	SaveUniversity(ctx context.Context, in *SaveUniversityRequest, opts ...grpc.CallOption) (*SaveUniversityResponse, error)
	GetSavedUniversities(ctx context.Context, in *GetSavedUniversitiesRequest, opts ...grpc.CallOption) (*GetSavedUniversitiesResponse, error)
	SearchGrants(ctx context.Context, in *SearchGrantsRequest, opts ...grpc.CallOption) (*SearchGrantsResponse, error)
	SaveGrant(ctx context.Context, in *SaveGrantRequest, opts ...grpc.CallOption) (*SaveGrantResponse, error)
	GetSavedGrants(ctx context.Context, in *GetSavedGrantsRequest, opts ...grpc.CallOption) (*GetSavedGrantsResponse, error)
	RemoveSavedUniversity(ctx context.Context, in *RemoveSavedUniversityRequest, opts ...grpc.CallOption) (*RemoveSavedUniversityResponse, error)
	RemoveSavedGrant(ctx context.Context, in *RemoveSavedGrantRequest, opts ...grpc.CallOption) (*RemoveSavedGrantResponse, error)
	GetGrantDetails(ctx context.Context, in *GetGrantDetailsRequest, opts ...grpc.CallOption) (*GetGrantDetailsResponse, error)
	ListUniversitiesByCategory(ctx context.Context, in *ListUniversitiesByCategoryRequest, opts ...grpc.CallOption) (*ListUniversitiesByCategoryResponse, error)
	GetUniversityStatistics(ctx context.Context, in *GetUniversityStatisticsRequest, opts ...grpc.CallOption) (*GetUniversityStatisticsResponse, error)
}

type universityServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUniversityServiceClient(cc grpc.ClientConnInterface) UniversityServiceClient {
	return &universityServiceClient{cc}
}

func (c *universityServiceClient) SearchUniversities(ctx context.Context, in *SearchUniversitiesRequest, opts ...grpc.CallOption) (*SearchUniversitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchUniversitiesResponse)
	err := c.cc.Invoke(ctx, UniversityService_SearchUniversities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *universityServiceClient) GetUniversityDetails(ctx context.Context, in *GetUniversityDetailsRequest, opts ...grpc.CallOption) (*GetUniversityDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUniversityDetailsResponse)
	err := c.cc.Invoke(ctx, UniversityService_GetUniversityDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *universityServiceClient) SaveUniversity(ctx context.Context, in *SaveUniversityRequest, opts ...grpc.CallOption) (*SaveUniversityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveUniversityResponse)
	err := c.cc.Invoke(ctx, UniversityService_SaveUniversity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *universityServiceClient) GetSavedUniversities(ctx context.Context, in *GetSavedUniversitiesRequest, opts ...grpc.CallOption) (*GetSavedUniversitiesResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSavedUniversitiesResponse)
	err := c.cc.Invoke(ctx, UniversityService_GetSavedUniversities_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *universityServiceClient) SearchGrants(ctx context.Context, in *SearchGrantsRequest, opts ...grpc.CallOption) (*SearchGrantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SearchGrantsResponse)
	err := c.cc.Invoke(ctx, UniversityService_SearchGrants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *universityServiceClient) SaveGrant(ctx context.Context, in *SaveGrantRequest, opts ...grpc.CallOption) (*SaveGrantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(SaveGrantResponse)
	err := c.cc.Invoke(ctx, UniversityService_SaveGrant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *universityServiceClient) GetSavedGrants(ctx context.Context, in *GetSavedGrantsRequest, opts ...grpc.CallOption) (*GetSavedGrantsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetSavedGrantsResponse)
	err := c.cc.Invoke(ctx, UniversityService_GetSavedGrants_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *universityServiceClient) RemoveSavedUniversity(ctx context.Context, in *RemoveSavedUniversityRequest, opts ...grpc.CallOption) (*RemoveSavedUniversityResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveSavedUniversityResponse)
	err := c.cc.Invoke(ctx, UniversityService_RemoveSavedUniversity_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *universityServiceClient) RemoveSavedGrant(ctx context.Context, in *RemoveSavedGrantRequest, opts ...grpc.CallOption) (*RemoveSavedGrantResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RemoveSavedGrantResponse)
	err := c.cc.Invoke(ctx, UniversityService_RemoveSavedGrant_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *universityServiceClient) GetGrantDetails(ctx context.Context, in *GetGrantDetailsRequest, opts ...grpc.CallOption) (*GetGrantDetailsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetGrantDetailsResponse)
	err := c.cc.Invoke(ctx, UniversityService_GetGrantDetails_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *universityServiceClient) ListUniversitiesByCategory(ctx context.Context, in *ListUniversitiesByCategoryRequest, opts ...grpc.CallOption) (*ListUniversitiesByCategoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListUniversitiesByCategoryResponse)
	err := c.cc.Invoke(ctx, UniversityService_ListUniversitiesByCategory_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *universityServiceClient) GetUniversityStatistics(ctx context.Context, in *GetUniversityStatisticsRequest, opts ...grpc.CallOption) (*GetUniversityStatisticsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetUniversityStatisticsResponse)
	err := c.cc.Invoke(ctx, UniversityService_GetUniversityStatistics_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UniversityServiceServer is the server API for UniversityService service.
// All implementations must embed UnimplementedUniversityServiceServer
// for forward compatibility.
type UniversityServiceServer interface {
	SearchUniversities(context.Context, *SearchUniversitiesRequest) (*SearchUniversitiesResponse, error)
	GetUniversityDetails(context.Context, *GetUniversityDetailsRequest) (*GetUniversityDetailsResponse, error)
	SaveUniversity(context.Context, *SaveUniversityRequest) (*SaveUniversityResponse, error)
	GetSavedUniversities(context.Context, *GetSavedUniversitiesRequest) (*GetSavedUniversitiesResponse, error)
	SearchGrants(context.Context, *SearchGrantsRequest) (*SearchGrantsResponse, error)
	SaveGrant(context.Context, *SaveGrantRequest) (*SaveGrantResponse, error)
	GetSavedGrants(context.Context, *GetSavedGrantsRequest) (*GetSavedGrantsResponse, error)
	RemoveSavedUniversity(context.Context, *RemoveSavedUniversityRequest) (*RemoveSavedUniversityResponse, error)
	RemoveSavedGrant(context.Context, *RemoveSavedGrantRequest) (*RemoveSavedGrantResponse, error)
	GetGrantDetails(context.Context, *GetGrantDetailsRequest) (*GetGrantDetailsResponse, error)
	ListUniversitiesByCategory(context.Context, *ListUniversitiesByCategoryRequest) (*ListUniversitiesByCategoryResponse, error)
	GetUniversityStatistics(context.Context, *GetUniversityStatisticsRequest) (*GetUniversityStatisticsResponse, error)
	mustEmbedUnimplementedUniversityServiceServer()
}

// UnimplementedUniversityServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedUniversityServiceServer struct{}

func (UnimplementedUniversityServiceServer) SearchUniversities(context.Context, *SearchUniversitiesRequest) (*SearchUniversitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchUniversities not implemented")
}
func (UnimplementedUniversityServiceServer) GetUniversityDetails(context.Context, *GetUniversityDetailsRequest) (*GetUniversityDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUniversityDetails not implemented")
}
func (UnimplementedUniversityServiceServer) SaveUniversity(context.Context, *SaveUniversityRequest) (*SaveUniversityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveUniversity not implemented")
}
func (UnimplementedUniversityServiceServer) GetSavedUniversities(context.Context, *GetSavedUniversitiesRequest) (*GetSavedUniversitiesResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSavedUniversities not implemented")
}
func (UnimplementedUniversityServiceServer) SearchGrants(context.Context, *SearchGrantsRequest) (*SearchGrantsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SearchGrants not implemented")
}
func (UnimplementedUniversityServiceServer) SaveGrant(context.Context, *SaveGrantRequest) (*SaveGrantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method SaveGrant not implemented")
}
func (UnimplementedUniversityServiceServer) GetSavedGrants(context.Context, *GetSavedGrantsRequest) (*GetSavedGrantsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetSavedGrants not implemented")
}
func (UnimplementedUniversityServiceServer) RemoveSavedUniversity(context.Context, *RemoveSavedUniversityRequest) (*RemoveSavedUniversityResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveSavedUniversity not implemented")
}
func (UnimplementedUniversityServiceServer) RemoveSavedGrant(context.Context, *RemoveSavedGrantRequest) (*RemoveSavedGrantResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RemoveSavedGrant not implemented")
}
func (UnimplementedUniversityServiceServer) GetGrantDetails(context.Context, *GetGrantDetailsRequest) (*GetGrantDetailsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetGrantDetails not implemented")
}
func (UnimplementedUniversityServiceServer) ListUniversitiesByCategory(context.Context, *ListUniversitiesByCategoryRequest) (*ListUniversitiesByCategoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ListUniversitiesByCategory not implemented")
}
func (UnimplementedUniversityServiceServer) GetUniversityStatistics(context.Context, *GetUniversityStatisticsRequest) (*GetUniversityStatisticsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetUniversityStatistics not implemented")
}
func (UnimplementedUniversityServiceServer) mustEmbedUnimplementedUniversityServiceServer() {}
func (UnimplementedUniversityServiceServer) testEmbeddedByValue()                           {}

// UnsafeUniversityServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UniversityServiceServer will
// result in compilation errors.
type UnsafeUniversityServiceServer interface {
	mustEmbedUnimplementedUniversityServiceServer()
}

func RegisterUniversityServiceServer(s grpc.ServiceRegistrar, srv UniversityServiceServer) {
	// If the following call panics, it indicates UnimplementedUniversityServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&UniversityService_ServiceDesc, srv)
}

func _UniversityService_SearchUniversities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchUniversitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UniversityServiceServer).SearchUniversities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UniversityService_SearchUniversities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UniversityServiceServer).SearchUniversities(ctx, req.(*SearchUniversitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UniversityService_GetUniversityDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUniversityDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UniversityServiceServer).GetUniversityDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UniversityService_GetUniversityDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UniversityServiceServer).GetUniversityDetails(ctx, req.(*GetUniversityDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UniversityService_SaveUniversity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveUniversityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UniversityServiceServer).SaveUniversity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UniversityService_SaveUniversity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UniversityServiceServer).SaveUniversity(ctx, req.(*SaveUniversityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UniversityService_GetSavedUniversities_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSavedUniversitiesRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UniversityServiceServer).GetSavedUniversities(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UniversityService_GetSavedUniversities_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UniversityServiceServer).GetSavedUniversities(ctx, req.(*GetSavedUniversitiesRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UniversityService_SearchGrants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SearchGrantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UniversityServiceServer).SearchGrants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UniversityService_SearchGrants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UniversityServiceServer).SearchGrants(ctx, req.(*SearchGrantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UniversityService_SaveGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SaveGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UniversityServiceServer).SaveGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UniversityService_SaveGrant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UniversityServiceServer).SaveGrant(ctx, req.(*SaveGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UniversityService_GetSavedGrants_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetSavedGrantsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UniversityServiceServer).GetSavedGrants(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UniversityService_GetSavedGrants_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UniversityServiceServer).GetSavedGrants(ctx, req.(*GetSavedGrantsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UniversityService_RemoveSavedUniversity_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSavedUniversityRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UniversityServiceServer).RemoveSavedUniversity(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UniversityService_RemoveSavedUniversity_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UniversityServiceServer).RemoveSavedUniversity(ctx, req.(*RemoveSavedUniversityRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UniversityService_RemoveSavedGrant_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveSavedGrantRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UniversityServiceServer).RemoveSavedGrant(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UniversityService_RemoveSavedGrant_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UniversityServiceServer).RemoveSavedGrant(ctx, req.(*RemoveSavedGrantRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UniversityService_GetGrantDetails_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetGrantDetailsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UniversityServiceServer).GetGrantDetails(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UniversityService_GetGrantDetails_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UniversityServiceServer).GetGrantDetails(ctx, req.(*GetGrantDetailsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UniversityService_ListUniversitiesByCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListUniversitiesByCategoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UniversityServiceServer).ListUniversitiesByCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UniversityService_ListUniversitiesByCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UniversityServiceServer).ListUniversitiesByCategory(ctx, req.(*ListUniversitiesByCategoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UniversityService_GetUniversityStatistics_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetUniversityStatisticsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UniversityServiceServer).GetUniversityStatistics(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UniversityService_GetUniversityStatistics_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UniversityServiceServer).GetUniversityStatistics(ctx, req.(*GetUniversityStatisticsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// UniversityService_ServiceDesc is the grpc.ServiceDesc for UniversityService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UniversityService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "university.UniversityService",
	HandlerType: (*UniversityServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "SearchUniversities",
			Handler:    _UniversityService_SearchUniversities_Handler,
		},
		{
			MethodName: "GetUniversityDetails",
			Handler:    _UniversityService_GetUniversityDetails_Handler,
		},
		{
			MethodName: "SaveUniversity",
			Handler:    _UniversityService_SaveUniversity_Handler,
		},
		{
			MethodName: "GetSavedUniversities",
			Handler:    _UniversityService_GetSavedUniversities_Handler,
		},
		{
			MethodName: "SearchGrants",
			Handler:    _UniversityService_SearchGrants_Handler,
		},
		{
			MethodName: "SaveGrant",
			Handler:    _UniversityService_SaveGrant_Handler,
		},
		{
			MethodName: "GetSavedGrants",
			Handler:    _UniversityService_GetSavedGrants_Handler,
		},
		{
			MethodName: "RemoveSavedUniversity",
			Handler:    _UniversityService_RemoveSavedUniversity_Handler,
		},
		{
			MethodName: "RemoveSavedGrant",
			Handler:    _UniversityService_RemoveSavedGrant_Handler,
		},
		{
			MethodName: "GetGrantDetails",
			Handler:    _UniversityService_GetGrantDetails_Handler,
		},
		{
			MethodName: "ListUniversitiesByCategory",
			Handler:    _UniversityService_ListUniversitiesByCategory_Handler,
		},
		{
			MethodName: "GetUniversityStatistics",
			Handler:    _UniversityService_GetUniversityStatistics_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "proto/university/university.proto",
}
