INSERT INTO universities (name, country, acceptance_rate, type, category) VALUES
('Massachusetts Institute of Technology', 'USA', 6.7, 'private', 'reach'),
('Stanford University', 'USA', 4.3, 'private', 'reach'),
('Harvard University', 'USA', 5.0, 'private', 'reach'),
('California Institute of Technology', 'USA', 7.0, 'private', 'reach'),
('Princeton University', 'USA', 5.8, 'private', 'reach'),
('Yale University', 'USA', 6.1, 'private', 'reach'),
('University of Oxford', 'UK', 17.5, 'public', 'reach'),
('University of Cambridge', 'UK', 21.0, 'public', 'reach'),
('Imperial College London', 'UK', 14.3, 'public', 'reach'),
('ETH Zurich', 'Switzerland', 27.0, 'public', 'target'),
('EPFL', 'Switzerland', 30.0, 'public', 'target'),
('National University of Singapore', 'Singapore', 5.0, 'public', 'reach'),
('Nanyang Technological University', 'Singapore', 12.0, 'public', 'reach'),
('University of Toronto', 'Canada', 43.0, 'public', 'target'),
('University of British Columbia', 'Canada', 52.0, 'public', 'target'),
('McGill University', 'Canada', 46.0, 'public', 'target'),
('Nazarbayev University', 'Kazakhstan', 30.0, 'public', 'target'),
('KAIST', 'South Korea', 25.0, 'public', 'target'),
('Seoul National University', 'South Korea', 35.0, 'public', 'target'),
('Technical University of Munich', 'Germany', 60.0, 'public', 'safety'),
('Heidelberg University', 'Germany', 50.0, 'public', 'target'),
('Humboldt University of Berlin', 'Germany', 55.0, 'public', 'target'),
('University of Tokyo', 'Japan', 35.0, 'public', 'target'),
('Kyoto University', 'Japan', 38.0, 'public', 'target'),
('Australian National University', 'Australia', 35.0, 'public', 'target'),
('University of Melbourne', 'Australia', 70.0, 'public', 'safety'),
('University of Sydney', 'Australia', 30.0, 'public', 'target'),
('Tsinghua University', 'China', 2.0, 'public', 'reach'),
('Peking University', 'China', 5.0, 'public', 'reach'),
('Sciences Po', 'France', 27.0, 'public', 'target');